### PR TITLE
Fixed a typo in README.md

### PR DESCRIPTION
**Pull request by SvA1**
A spelling typo: bear -> beer

### CODE REVIEW

**Comment by nlepage** [comment]
There is the same typo in [test/en.ts](https://github.com/nlepage/templural/blob/main/test/en.ts#L20), could you also fix it in this PR?
Thanks!

**Comment by SvA1** [comment]
> There is the same typo in [test/en.ts](https://github.com/nlepage/templural/blob/main/test/en.ts#L20), could you also fix it in this PR? Thanks!

Sorry, seems like I've just created another PR instead of adding it to this...

**Comment by nlepage** [comment]
> Sorry, seems like I've just created another PR instead of adding it to this...

No problem.

**Review by nlepage — APPROVED** [review]

**Comment by nlepage** [comment]
@all-contributors please add @SvA1 for doc

**Pull request merged**
